name: Build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Make release
        run: |
          cd target/debug/
          ./make_release.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zapret-discord-youtube-ankddev-debug
          path: |
            target/debug/zapret-discord-youtube-ankddev.zip
