name: Release
on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
      - name: Build and make release
        run: |
          scripts/build.bat
      - name: Rename archive
        run: Rename-Item -Path build/zapret-discord-youtube-ankddev.zip -NewName zapret-discord-youtube-ankddev-${{ github.event.release.tag_name }}.zip
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: build/zapret-discord-youtube-ankddev-${{ github.event.release.tag_name }}.zip

